from docx import Document
from pptx import Presentation
import os

OUTPUT_DIR = "generated_docs"
if not os.path.exists(OUTPUT_DIR):
    os.makedirs(OUTPUT_DIR)

def generate_word_doc(project_title, sections):
    doc = Document()
    doc.add_heading(project_title, 0)

    for section in sections:
        doc.add_heading(section.title, level=1)
        doc.add_paragraph(section.content or "No content generated yet.")

    filename = f"{project_title.replace(' ', '_')}.docx"
    filepath = os.path.join(OUTPUT_DIR, filename)
    doc.save(filepath)
    return filepath

def generate_ppt_doc(project_title, sections):
    prs = Presentation()
    title_slide_layout = prs.slide_layouts[0]
    slide = prs.slides.add_slide(title_slide_layout)
    slide.shapes.title.text = project_title
    slide.placeholders[1].text = "Generated by AI Platform"

    for section in sections:
        bullet_slide_layout = prs.slide_layouts[1]
        slide = prs.slides.add_slide(bullet_slide_layout)
        shapes = slide.shapes
        shapes.title.text = section.title
        shapes.placeholders[1].text = section.content or "No content."

    filename = f"{project_title.replace(' ', '_')}.pptx"
    filepath = os.path.join(OUTPUT_DIR, filename)
    prs.save(filepath)
    return filepath